import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Ecosystem,SPECIES,PLANTS,MAX_CELLS,MAX_CREATURES,inWater} from '../dist/simulation.js';
import {genome,TRAITS,seedRandom} from '../dist/genetics.js';
import {World} from '../dist/world.js';
const root=new URL('../',import.meta.url),html=fs.readFileSync(new URL('dist/index.html',root),'utf8'),app=fs.readFileSync(new URL('dist/app.js',root),'utf8');
for(const [,id] of app.matchAll(/\$\('([^']+)'\)/g))assert(html.includes('id="'+id+'"'),'Missing element '+id);
for(const [,file] of html.matchAll(/(?:src|href)="\.\/([^"#]+)"/g))assert(fs.existsSync(new URL('dist/'+file,root)),'Missing asset '+file);
const checks=[];
// Every allele is inherited from the correct parent's pool or explicitly mutated.
const mother=genome(912),father=genome(830);for(let seed=1;seed<100;seed++){const child=genome(seed,mother,father);assert.deepEqual(child,genome(seed,mother,father));for(const key of Object.keys(TRAITS)){for(const i of [0,1]){if(!child.mutations.some(m=>m.trait===key&&m.allele===i))assert((i===0?mother:father).alleles[key].includes(child.alleles[key][i]));}assert.equal(child.traits[key],(child.alleles[key][0]+child.alleles[key][1])/2);}}
checks.push('deterministic diploid inheritance and mutation records');
const sim=new Ecosystem();const m=sim.creatures.find(c=>c.species===0&&c.sex==='M'),f=sim.creatures.find(c=>c.species===0&&c.sex==='F');Object.assign(m,{x:1,z:1,age:7,energy:100,cooldown:0});Object.assign(f,{x:1.2,z:1.2,age:7,energy:100,cooldown:0});assert(sim.court(m,f));assert.equal(m.stage,'court');for(let i=0;i<160;i++)sim.progressPair(m,.1);assert(f.pregnancy);assert.equal(f.pregnancy.father,m.id);f.pregnancy.remaining=0;sim.giveBirth(f);const baby=sim.creatures.at(-1);assert.equal(baby.mother,f.id);assert.equal(baby.father,m.id);assert.equal(sim.births,1);assert.equal(f.children,1);assert.equal(m.children,1);assert.equal(baby.age,0);assert(sim.events.some(e=>e.kind==='birth'));
const before=baby.dna.revision;sim.intervene('mutate',baby.x,baby.z);assert(sim.creatures.some(c=>c.dna.revision>0));checks.push('courtship, male/female mating, gestation, biparental birth');
const dead=sim.creatures[5],oldNutrients=sim.nutrientsReturned;sim.kill(dead,'completó su ciclo');assert(sim.remains.some(r=>r.id===dead.id));for(let i=0;i<750;i++)sim.step(.1);assert(sim.nutrientsReturned>oldNutrients);assert(!sim.remains.some(r=>r.id===dead.id));assert(sim.archive.some(c=>c.id===dead.id));assert(sim.events.some(e=>e.kind==='compost'));checks.push('death, corpse persistence, decomposition and nutrient return');
const plantSim=new Ecosystem();plantSim.creatures=[];plantSim.reindex();plantSim.food=[{id:999,x:0,z:0,type:0,growth:1,age:PLANTS[0].life+1,biomass:5,seed:1,soilFed:0}];plantSim.step(.1);assert.equal(plantSim.plantDeaths,1);assert.equal(plantSim.nutrientsReturned,5);plantSim.addFood({x:0,z:0},.1,0);plantSim.step(.1);assert(plantSim.food[0].soilFed>0);checks.push('dead vegetation fertilizes growing vegetation');
const v1={snapshot:()=>JSON.parse(fs.readFileSync(new URL('scripts/fixtures/v1-world.json',root),'utf8'))};const v2=new Ecosystem(v1.snapshot());assert.equal(v2.version,4);assert.equal(v2.creatures[0].name,'Nombre conservado');assert(v2.creatures.some(c=>c.species===4));assert(v2.creatures.some(c=>c.species===5));const restored=new Ecosystem(JSON.parse(JSON.stringify(v2.snapshot())));assert.deepEqual(restored.creatures,v2.creatures);assert.equal(restored.worldSeed,v2.worldSeed);checks.push('v1 migration preserves names and world; v2 save roundtrip');
const long=new Ecosystem();long.expand();long.expand();long.expand();assert.equal(long.radius,39);assert.equal(long.capacity,126);const radius=long.radius;long.expand();assert.equal(long.radius,radius);const durations=[];
for(let i=0;i<36000;i++){const t=performance.now();long.step(.1);if(i>200)durations.push(performance.now()-t);assert(long.creatures.length<=long.capacity);assert(long.food.length<=long.foodCapacity);if(i%100===0){for(const c of long.creatures){assert(Number.isFinite(c.x+c.z+c.age+c.health+c.energy));assert(SPECIES[c.species].habitat==='water'?inWater(c.x,c.z):!inWater(c.x,c.z));}assert.equal(new Set(long.creatures.map(c=>c.dna.seed)).size,long.creatures.length);}}
assert(long.births>0&&long.deaths>0&&long.creatures.length>0);checks.push('three expansions, habitat confinement, seed uniqueness and one simulated hour');
const dense=new Ecosystem();dense.expand();dense.expand();dense.expand();while(dense.creatures.length<dense.capacity){const sp=dense.creatures.length%6;dense.create(sp,dense.point(sp));}
const w=Object.create(World.prototype);Object.assign(w,{sim:dense,actors:new Map(),cellCounts:new Map(),cellTemplates:SPECIES.map(t=>World.prototype.makeTemplate.call({},t)),cellMatrices:new Float32Array((MAX_CREATURES+64)*MAX_CELLS*16),cellColors:new Float32Array((MAX_CREATURES+64)*MAX_CELLS*3),owners:[],cellIndex:0,boneIndex:0,skeleton:false,qualityTier:0,distance:30,frame:0});
const frameTimes=[];for(let i=0;i<240;i++){const t=performance.now();w.cellIndex=0;for(const c of dense.creatures)w.renderCreature(c,1/60);if(i>30)frameTimes.push(performance.now()-t);w.frame++;}
for(let i=0;i<w.cellIndex*16;i++)assert(Number.isFinite(w.cellMatrices[i]),'Non-finite transformation');for(const count of w.cellCounts.values())assert(count<=MAX_CELLS);const counts=Object.fromEntries(SPECIES.map(s=>[s.name,w.cellCounts.get(dense.creatures.find(c=>c.species===s.id).id)]));
for(const c of dense.creatures.slice(0,6)){for(const state of ['Comiendo','Descansando','Cazando','Huyendo']){c.state=state;w.cellIndex=0;w.renderCreature(c,1/60);}dense.kill(c,'completó su ciclo');}w.cellIndex=0;for(const r of dense.remains){r.life=1;w.renderCreature(r,1/60,true);}for(let i=0;i<w.cellIndex*16;i++)assert(Number.isFinite(w.cellMatrices[i]));checks.push('six locomotion models, living/dead transforms and cell budgets');
const p95=arr=>arr.sort((a,b)=>a-b)[Math.floor(arr.length*.95)];const result={passed:true,checks,cells:counts,simulatedHour:{population:long.creatures.length,species:long.counts,births:long.births,deaths:long.deaths,nutrients:Math.round(long.nutrientsReturned)},cpuBenchmarks:{simulationStepP95ms:+p95(durations).toFixed(3),creaturePreparationP95ms:+p95(frameTimes).toFixed(3),agents:126,note:'Node CPU only; excludes WebGL, GPU, browser layout and display timing. Does not certify 60 FPS.'}};console.log(JSON.stringify(result,null,2));fs.writeFileSync(new URL('verification.json',root),JSON.stringify(result,null,2)+'\n');
