import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Ecosystem,MAX_CREATURES} from '../dist/simulation.js';
import {StateEncoder,StateDecoder} from '../dist/state-channel.js';
import {FrameBudget,GpuTimer,TIERS,lodLevel,pixelRatio} from '../dist/render-budget.js';
import {GlobeWorld} from '../dist/globe.js';
import {mutateGenome} from '../dist/genetics.js';
const sim=new Ecosystem(),encoder=new StateEncoder(),decoder=new StateDecoder(),wire=p=>structuredClone(p);let packet=encoder.encode(sim.snapshot(),true);assert.deepEqual(decoder.decode(wire(packet)),sim.snapshot());
let bytesFull=0,bytesDelta=0;
for(let i=0;i<40;i++){sim.step(.1);if(i%2===0){const full=sim.snapshot();packet=encoder.encode(full);bytesFull+=Buffer.byteLength(JSON.stringify(full));bytesDelta+=Buffer.byteLength(JSON.stringify(packet));assert.deepEqual(decoder.decode(wire(packet)),full);}}
const c=sim.creatures[0];mutateGenome(c.dna,()=>sim.random());packet=encoder.encode(sim.snapshot());assert(packet.state.creatures[0].dna);assert.deepEqual(decoder.decode(wire(packet)),sim.snapshot());sim.kill(c,'completó su ciclo');assert.deepEqual(decoder.decode(wire(encoder.encode(sim.snapshot()))),sim.snapshot());sim.archive[0].name='Memoria conservada';assert.deepEqual(decoder.decode(wire(encoder.encode(sim.snapshot(),true))),sim.snapshot());const reset=new Ecosystem();assert.deepEqual(decoder.decode(wire(encoder.encode(reset.snapshot(),true))),reset.snapshot());assert(bytesDelta<bytesFull*.85);
// The renderer works within hard bounds even with an unusually dense group.
while(sim.creatures.length<MAX_CREATURES){const parent=sim.creatures[0];sim.create(parent.species,{x:parent.x,z:parent.z});}sim.reindex();sim.time+=.1;
globalThis.innerWidth=1920;globalThis.innerHeight=1080;globalThis.devicePixelRatio=2;globalThis.window={addEventListener(){}};
let ratio=1;const renderer={domElement:{style:{},addEventListener(){}},shadowMap:{},setPixelRatio(v){ratio=v;},getPixelRatio(){return ratio;},setSize(){},render(s,c){s.updateMatrixWorld();c.updateMatrixWorld();},info:{render:{calls:0}}};
const world=new GlobeWorld({appendChild(){}},sim,{renderer});world.select(sim.creatures[0].id,true);world.distance=world.desiredDistance=9;const unchanged=JSON.stringify(sim.snapshot()),counts=[];
for(let tier=0;tier<3;tier++){world.setQuality(tier);for(let i=0;i<12;i++)world.render(1/60);assert(world.cellIndex<=TIERS[tier].cells);assert(world.foodMesh.count<=TIERS[tier].plants);assert(world.seedMesh.count<=240);assert(world.dots.count<=MAX_CREATURES);assert(innerWidth*innerHeight*ratio*ratio<=TIERS[tier].pixels+1);assert.equal(world.effects.clouds.visible,tier<2&&world.distance>18.5);counts.push({tier,cells:world.cellIndex,plants:world.foodMesh.count,markers:world.dots.count,pixelRatio:ratio});}
assert.equal(JSON.stringify(sim.snapshot()),unchanged);assert(world.lodStats.hidden>0);assert.equal(lodLevel(40,0,0),0);assert.equal(lodLevel(40,1,0),1);assert.equal(lodLevel(12,1,0),1);assert.equal(lodLevel(12,2,0),2);assert.equal(lodLevel(100,0,2),1);assert(pixelRatio(7680,4320,2,0)<.32);
const budget=new FrameBudget();let tier=0;for(let i=0;i<400;i++)tier=budget.add(30,.03,tier);assert(tier>0);const fixed=tier;for(let i=0;i<120;i++)tier=budget.add(16.67,1/60,tier);assert(tier>=fixed);const worst=tier;budget.reset();for(let i=0;i<2400;i++)tier=budget.add(16.67,1/60,tier);assert(tier<worst);
const stalled=new FrameBudget();let slowTier=0;for(let i=0;i<80;i++)slowTier=stalled.add(500,.25,slowTier);assert(slowTier>0,'Long foreground stalls must reduce quality');
// Driver results are polled only after availability; disjoint invalidates all pending results.
let available=false,disjoint=false,queried=0,deleted=0;const gl={QUERY_RESULT_AVAILABLE:1,QUERY_RESULT:2,getExtension:()=>({TIME_ELAPSED_EXT:3,GPU_DISJOINT_EXT:4}),getParameter:()=>disjoint,getQueryParameter(q,p){if(p===1)return available;assert(available);queried++;return 4e6;},createQuery:()=>({}),beginQuery(){},endQuery(){},deleteQuery(){deleted++;}};
const timer=new GpuTimer({getContext:()=>gl});for(let i=0;i<10;i++){timer.begin();timer.end();}assert.equal(timer.pending.length,4);assert.equal(queried,0);available=true;timer.begin();timer.end();assert.equal(timer.ms,4);assert.equal(deleted,4);disjoint=true;timer.begin();assert.equal(timer.ms,null);assert.equal(timer.pending.length,0);timer.dispose();new GpuTimer({}).begin();
fs.writeFileSync(new URL('../verification-scale.json',import.meta.url),JSON.stringify({passed:true,checks:['lossless full/delta worker channel, mutations, death/archive, reset','hard cell/plant/pixel budgets at 384 inhabitants','LOD hysteresis and render/data isolation','frame percentile controller with recovery delay','bounded nonblocking GPU queries and disjoint handling'],transport:{fullBytes:bytesFull,deltaBytes:bytesDelta,reductionPercent:+((1-bytesDelta/bytesFull)*100).toFixed(1)},renderBudgets:counts,limits:'Node transport and Three.js math with injected renderer. GPU timer tested with a driver double; not real-device FPS.'},null,2)+'\n');console.log('PASS: compact state channel, dense render budgets, LOD stability and asynchronous GPU timer.');
