import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Ecosystem,MAX_CREATURES,MAX_CELLS} from '../dist/simulation.js';
import {genome,TRAITS} from '../dist/genetics.js';
import {ACTIONS} from '../dist/culture.js';
import {GlobeWorld} from '../dist/globe.js';
import {HALF,POLE,PLANET_RADIUS as R,xyz,coordinates,move,distance,geography,climateAt,SOLAR_DAY,YEAR,adaptation} from '../dist/planet.js';
const checks=[],p95=a=>a.sort((x,y)=>x-y)[Math.floor(a.length*.95)];
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');for(const [,id] of app.matchAll(/\$\('([^']+)'\)/g))assert(html.includes('id="'+id+'"'),'Missing element '+id);for(const [,path] of html.matchAll(/(?:src|href)="\.\/([^"#]+)"/g))assert(fs.existsSync(new URL('../dist/'+path,import.meta.url)));
for(const z of [-POLE+.01,-35,0,35,POLE-.01])for(const x of [-HALF+.01,-60,0,HALF-.01]){const p={x,z},w=xyz(x,z);assert(Math.abs(Math.hypot(w.x,w.y,w.z)-R)<1e-8);assert(distance(p,coordinates(w))<1e-5);const q=move(x,z,.15,.12);assert(Math.abs(distance(p,q)-Math.hypot(.15,.12))<1e-6);assert(Math.abs(q.z)<=POLE);}
assert(distance({x:HALF-.1,z:0},{x:-HALF+.1,z:0})<.201);assert(climateAt(0,0,0).light>.99);assert.equal(climateAt(HALF,0,0).light,0);assert(climateAt(0,0,0).temperature>climateAt(0,0,SOLAR_DAY/2).temperature);assert(climateAt(0,35,YEAR/4).temperature>climateAt(0,35,YEAR*3/4).temperature);assert(Math.abs(geography(-HALF,17).height-geography(HALF,17).height)<1e-12);checks.push('spherical projection, seam and poles, opposite day/night, hemispheric seasons');
for(let seed=1;seed<80;seed++){const a=genome(12),b=genome(84),c=genome(seed,a,b);assert.deepEqual(c,genome(seed,a,b));for(const key of Object.keys(TRAITS))for(const i of [0,1])if(!c.mutations.some(m=>m.trait===key&&m.allele===i))assert((i===0?a:b).alleles[key].includes(c.alleles[key][i]));}
const s=new Ecosystem(),female=s.creatures.find(c=>c.species===0&&c.sex==='F'),male=s.creatures.find(c=>c.species===0&&c.sex==='M'),p=s.point(0,0);Object.assign(female,p,{energy:100,cooldown:0,age:5});Object.assign(male,move(p.x,p.z,.4,0),{energy:100,cooldown:0,age:5});female.mind.practice.materials=[0,2,0,0];female.mind.practice.routes=[{...p,value:.5,action:'rest'}];assert(s.court(male,female));for(let i=0;i<160;i++)s.progressPair(male,.1);assert(female.pregnancy);s.giveBirth(female);const baby=s.creatures.at(-1);assert.equal(baby.mother,female.id);assert.equal(baby.father,male.id);assert(baby.mind.practice.materials[1]>0);assert(baby.mind.practice.routes.length);const clone=structuredClone(baby);clone.dna.traits.insulation=0;const other=structuredClone(baby);other.dna.traits.insulation=1;assert(adaptation(clone,climateAt(0,40,0)).cost!==adaptation(other,climateAt(0,40,0)).cost);checks.push('diploid inheritance, morphology cost, courtship, birth, parental cultural transmission');
const agent=s.creatures[2];Object.assign(agent,p,{energy:90,stage:null});agent.mind.carrying={type:2};agent.mind.job={action:'place',...p,until:s.time+4};assert(s.culture.updateAgent(agent,.1));const block=s.culture.blocks.at(-1);assert(block);assert(!agent.mind.carrying);assert(s.culture.habitat(p.x,p.z).moisture>0);block.health=.3;agent.mind.carrying={type:2};agent.mind.job={action:'repair',id:block.id,x:block.x,z:block.z,until:s.time+4};s.culture.updateAgent(agent,.1);assert(block.health>.3);assert(!agent.mind.carrying);agent.mind.job={action:'remove',id:block.id,x:block.x,z:block.z,until:s.time+4};s.culture.updateAgent(agent,.1);assert(!s.culture.blocks.includes(block));assert.equal(agent.mind.carrying.type,2);assert(!ACTIONS.some(a=>/city|house|war/.test(a)));checks.push('material conservation on place/repair/remove and measurable moisture retention');
const seamChild=s.create(5,{x:HALF+.1,z:0});assert(seamChild.x<HALF&&seamChild.x>=-HALF);
const legacy=JSON.parse(fs.readFileSync(new URL('fixtures/v1-world.json',import.meta.url),'utf8')),migrated=new Ecosystem(legacy);assert.equal(migrated.version,5);assert.equal(migrated.creatures[0].name,'Nombre conservado');const restored=new Ecosystem(migrated.snapshot());assert.deepEqual(restored.creatures,migrated.creatures);const snapshot=s.snapshot(),one=new Ecosystem(snapshot),two=new Ecosystem(snapshot);for(let i=0;i<30;i++){one.step(.1);two.step(.1);}assert.deepEqual(one.snapshot(),two.snapshot());checks.push('migration preserves names and lineage, deterministic independent save continuation');
globalThis.innerWidth=1440;globalThis.innerHeight=900;globalThis.devicePixelRatio=1;globalThis.window={addEventListener(){}};const renderer={domElement:{style:{},addEventListener(){}},shadowMap:{},setPixelRatio(){},setSize(){},render(s,c){s.updateMatrixWorld();c.updateMatrixWorld();},info:{render:{calls:0}}};const world=new GlobeWorld({appendChild(){}},one,{renderer});world.render(.016);assert(world.lodStats.hidden>0);assert(world.lodStats.dots>0);const immutable=JSON.stringify(one.snapshot());world.select(one.creatures[0].id,true);const times=[];for(let i=0;i<100;i++){world.render(1/60);if(i>20)times.push(world.renderMs);}assert.equal(JSON.stringify(one.snapshot()),immutable);assert(world.cellIndex>0);for(let i=0;i<world.cellIndex*16;i++)assert(Number.isFinite(world.cellMatrices[i]));for(const n of world.cellCounts.values())assert(n<=MAX_CELLS);world.toggleSkeleton();world.render(.016);assert(world.boneIndex>0);world.focus={x:-HALF+.1,z:POLE-.2};world.following=false;world.render(.016);assert(world.camera.position.toArray().every(Number.isFinite));world.zoom(.000001);assert.equal(world.desiredDistance,5);world.zoom(1e8);assert.equal(world.desiredDistance,190);checks.push('real Three.js geometry, finite IK, polar navigation, LOD/horizon and render/data isolation');
const long=new Ecosystem(),durations=[],seed=long.worldSeed,dead=long.creatures[0];long.kill(dead,'completó su ciclo');const nutrients=long.nutrientsReturned;for(let i=0;i<12000;i++){const t=performance.now();long.step(.1);if(i>100)durations.push(performance.now()-t);if(i%100===0){assert(long.creatures.length<=MAX_CREATURES);assert(long.food.length<=2400);assert(long.culture.blocks.length<=1400);assert(long.culture.materials.length<=420);for(const c of long.creatures){assert(Number.isFinite(c.energy+c.x+c.z+c.health));assert(Math.abs(c.z)<=POLE);assert(c.x>=-HALF&&c.x<HALF);assert(long.valid(c.x,c.z,c.species,c),'invalid habitat '+JSON.stringify({id:c.id,x:c.x,z:c.z,state:c.state,age:c.age,genes:c.dna.traits,geo:geography(c.x,c.z)}));}assert.equal(new Set(long.creatures.map(c=>c.dna.seed)).size,long.creatures.length);for(const c of long.creatures){assert(c.mind.knowledge.length<=8);assert(Object.keys(c.social.bonds).length<=8);assert(c.ecology.seeds.length<=3);}assert(long.lifeways.traditions.length<=96);assert(long.lifeways.lost.length<=24);assert(long.recovery.seeds.length<=1200);assert(new Set(long.recovery.seeds.map(s=>s.id)).size===long.recovery.seeds.length);for(const s of long.recovery.seeds)assert(Number.isFinite(s.viability+s.x+s.z));}}
assert(long.births>0&&long.deaths>0&&long.creatures.length>0);assert(long.nutrientsReturned>nutrients);assert(!long.remains.some(r=>r.id===dead.id));assert(long.culture.totals.placed>0);for(const key of ['care','transmissions','forgotten','pollinations','dispersed','germinated'])assert(long.lifeways.totals[key]>0,key+' must occur without intervention');checks.push('autonomous care, transmission/forgetting, cross-pollination, seed dispersal and bounded social memory');checks.push('20 simulated minutes: population/material bounds, valid habitats, births, deaths, nutrients, learning');
const result={passed:true,checks,observed:{seed,seconds:long.time,population:long.creatures.length,births:long.births,deaths:long.deaths,plants:long.food.length,pieces:long.culture.blocks.length,groups:long.culture.groups.length,migrations:long.migrations,activity:long.culture.totals,lifeways:long.lifeways.totals,recovery:long.recovery.totals,seedBank:long.recovery.seeds.length,sharedPractices:long.lifeways.traditions.filter(t=>t.holders>1).length,snapshotBytes:Buffer.byteLength(JSON.stringify(long.snapshot())),plantGenerations:Math.max(...long.food.map(f=>f.genes?.generation||1))},cpu:{stepP95ms:+p95(durations).toFixed(3),closeViewPreparationP95ms:+p95(times).toFixed(3)},limits:'Node CPU and real Three.js geometry only. No browser/GPU verification or universal 60 FPS guarantee. Six anatomical families; local learned practices, not guaranteed civilizations.'};fs.writeFileSync(new URL('../verification-v4.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
